"""empty message

Revision ID: 028220f4d504
Revises: 4a4077a9fdda
Create Date: 2020-04-30 12:56:08.654131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028220f4d504'
down_revision = '4a4077a9fdda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('address', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'address')
    # ### end Alembic commands ###
