"""empty message

Revision ID: 71a4b34f89cd
Revises: 93f7a0ae8646
Create Date: 2020-04-29 20:35:26.640250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a4b34f89cd'
down_revision = '93f7a0ae8646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post2_tag2',
    sa.Column('post2_id', sa.Integer(), nullable=True),
    sa.Column('teg2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post2_id'], ['post2.id'], ),
    sa.ForeignKeyConstraint(['teg2_id'], ['tag2.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post2_tag2')
    op.drop_table('post2')
    # ### end Alembic commands ###
