"""empty message

Revision ID: 8a620bd8d77f
Revises: c2af0ecc9862
Create Date: 2020-04-29 20:44:51.199148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a620bd8d77f'
down_revision = 'c2af0ecc9862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post2_tag2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post2_tag2',
    sa.Column('post2_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('teg2_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post2_id'], ['post2.id'], name='post2_tag2_ibfk_1'),
    sa.ForeignKeyConstraint(['teg2_id'], ['tag2.id'], name='post2_tag2_ibfk_2'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
