"""empty message

Revision ID: 93f7a0ae8646
Revises: da7d22a7e2de
Create Date: 2020-04-29 20:27:31.526335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93f7a0ae8646'
down_revision = 'da7d22a7e2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tag')
    op.drop_constraint('post_tag_ibfk_2', 'post_tag', type_='foreignkey')
    op.create_foreign_key(None, 'post_tag', 'tag2', ['teg_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_tag', type_='foreignkey')
    op.create_foreign_key('post_tag_ibfk_2', 'post_tag', 'tag', ['teg_id'], ['id'])
    op.create_table('tag',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tag2')
    # ### end Alembic commands ###
