"""empty message

Revision ID: b203765431e5
Revises: 32d36d25c11f
Create Date: 2020-05-06 18:19:57.226326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b203765431e5'
down_revision = '32d36d25c11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'created')
    # ### end Alembic commands ###
